services:
  db:
    image: dollysarmiento2024/bbdd:v1
    container_name: contenedor_bbdd
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: stadium
      MYSQL_USER: root
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
  php:
    image: dollysarmiento2024/app:v1
    container_name: contenedor_app
    ports:
      - "8080:80"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: contenedor_php_myadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "8081:80"
    depends_on:
      - db